### ISSUE TITLE
Chatlog function

### ISSUE THREAD

**Issue by RaistlinRTCW** [miltann/Echelon-2#11]
Hi
Great version of echelon as the old version I had , was not working when the database for b3 was moved. Installed this version and all good, just I notice you say chatlog function still to be worked on. Is that on the list of things to be done still ?
regards

**Comment by miltann** [comment]
Hey, thanks for your issue. Chatlog function does work. I assume you mean that it hasn't been implemented into the design yet. This will surely bei worked on in the near future.

**Comment by RaistlinRTCW** [comment]
Hi yes sorry so meant the being able to view the chatlog in the new design. I can see the logs in the database level fine so I know it is logging ok :-) You know how admins are they miss being able to see what people said, but hey they have access now which they haven't had for a few months since the move to see ban history ban players unban players etc

**Comment by miltann** [comment]
Not sure if I understood correctly, you should be able to see chatlogs from a specific user (with no context) like this:
![image](https://user-images.githubusercontent.com/34897878/55748725-ad649380-5a3f-11e9-801d-b0ada1ad461e.png)
If you can't see it, make sure its enabled in the game settings.

**Comment by RaistlinRTCW** [comment]
Hi
I have my COD WaW server setup and my connection to my b3 database with chat logs enabled. But on the main chat logs so Other --> Chatlogs where you would enter your chat log table I get the following error though the table does exist in the database 

Error! There was a problem. Maybe the table names you gave us are incorrect.

**Comment by miltann** [comment]
Will be worked on.

**Comment by RaistlinRTCW** [comment]
Thank you , much appreciated, very impressed with the clean look of this version compared to the version we had before and very happy with the performance and how easy it was to setup .

**Comment by miltann** [comment]
Your issue has been adressed, replace ``echelon\classes\dbl-class.php`` and ``echelon\lib\plugins\chatlogs\class.php`` in your Echelon installation.

**Comment by RaistlinRTCW** [comment]
Perfect thank you have updated them and now can add the chat log table and see the results , thank you for the quick turn around

**Comment by RaistlinRTCW** [comment]
Quick question I can see where I can change how many lines of chat on the chat log page, but where would I change it if I want to increase the number of lines of chat at the bottom of the client page?
