### ISSUE TITLE
Database in websitelink

### ISSUE THREAD

**Issue by fRAIKZz** [miltann/Echelon-2#19]
If you have multiple databases, it is not possible to link a client in a different database. 

Is there a possibility to add this into the link like: clientdetails.php?id=393&db=DBNAME

**Comment by miltann** [comment]
Instead of "db=xx", try "game=xx". You can see which game has which number in the url when you switch the games, if you added multiple games to echelon.

**Comment by fRAIKZz** [comment]
I see, that works. But this is not standard linked into the address bar. Is there a possibility to add that to it?

**Comment by fRAIKZz** [comment]
Any update?

**Comment by miltann** [comment]
Yes, it's possible. However, I'm not actively working on Echelon. There are a lot of issues that need to be fixed, which would talke a lot of time and effort, so there probably won't be a big update soon.

**Comment by miltann** [comment]
![grafik](https://user-images.githubusercontent.com/34897878/93996921-1efae380-fd93-11ea-9997-b619f6f33ec8.png)

You can now copy your client url directly into your clipboard using the button next to the client name. Replace clientdetails,php, cd.js and add link.png to your Echelon installation. Check the respective commit for more details.
