### ISSUE TITLE
Global Search GUI Error

### ISSUE THREAD

**Issue by james30263** [miltann/Echelon-2#9]
When you use the global search in the top right hand corner of GUI it sends you to the following link. <home directory>/echelon-v2/login.php.

**Comment by miltann** [comment]
It's a known bug and I haven't identified the root cause of it yet. However, the error didn't occur after creating a new account/search did work after 2nd login. Contact your site administrator to setup a new account for you, it might fix the issue.

**Comment by miltann** [comment]
I've pushed a new update and it should be fixed now. Please confirm.
